name: 'SQLFluff Action'
description: 'Uses Typescript to run SQLFluff'
author: 'tetracionist'

branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  sqlfluff-dialect:
    description: 'What dialect should sqlfluff use to check?'
    required: true
    default: 'snowflake'

  sqlfluff-templater:
    description: 'What templater should be used (e.g. dbt)?'
    required: false
    default: 'jinja'

  sqlfluff-mode:
    description: 'What mode should we use (lint or fix)'
    required: false
    default: 'lint'

  dbt-project-path:
    description: 'Where is the dbt project?'
    required: false

  dbt-profiles-path:
    description: 'Where are the dbt profiles?'
    required: false

  dbt-target:
    description: 'Which target should we use'
    required: false

  depedencies-path:
    description:
      'Path to the pyproject.toml or requirements.txt file (optional)'
    required: false

  review-dog-filter-mode:
    description: Strategy for filtering the linting results
    default: file
    required: false

  review-dog-name:
    description: 'Name of the linter'
    required: false
    default: 'sqlfluff-lint'

  review-dog-fail-on-error:
    description: 'Should reviewdog fail if linting violations are found?'
    required: false
    default: true

outputs:
  sqlfluff-version:
    description: 'The version of sqlfluff that was used'

runs:
  using: node20
  main: dist/index.js
