name: 'SQLFluff Action'
description: 'Uses Typescript to run SQLFluff'
author: 'tetracionist'

branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  sqlfluff-dialect:
    description: 'What dialect should sqlfluff use to check?'
    required: true
    default: 'snowflake'

  sqlfluff-templater:
    description: 'What templater should be used (e.g. dbt)?'
    required: false
    default: 'jinja'

  dbt-project-path:
    description: 'Where is the dbt project?'
    required: false

  dbt-profiles-path:
    description: 'Where are the dbt profiles?'
    required: false

  dbt-target:
    description: 'Which target should we use'
    required: false

  pyproject-path:
    description: 'Path to the pyproject.toml file (optional)'
    required: false

  github-token:
    description: 'GitHub token for accessing the API'
    required: true

  review-dog-filter-mode:
    description:
    default: file
    required: false

outputs:
  sqlfluff-version:
    description: 'The version of sqlfluff that was used'

runs:
  using: node20
  main: dist/index.js
